server:
  port: 9093
  
eureka:
  client:
    service-url: 
      defaultZon: http://localhost:8761/eureka/
      
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    password: root
    username: postgres
    driver-class-name:  org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
         